##########
#  VIEW  #
##########


jeb.snahp.routing.digg.mydigg:
    path: /snahp/digg/mydigg
    defaults: { _controller: jeb.snahp.Apps.Digg.DiggController:mydigg}

jeb.snahp.routing.digg.api.mydigg:
    path: /snahp/digg/api/mydigg
    defaults: { _controller: jeb.snahp.Apps.Digg.DiggController:apiMyDigg}
