jeb.snahp.routing.request_manager.change_solver:
    path: /snahp/request-manager/change-solver/topic/{topicId}/solver/{solverId}
    defaults: { _controller: jeb.snahp.Apps.RequestManager.RequestManagerController:changeSolver}
    requirements:
        topicId: \d+
        solverId: \d+
jeb.snahp.routing.request_manager.change_solver_with_username:
    path: /snahp/request-manager/change-solver/topic/{topicId}/solver-username/{solverUsername}
    defaults: { _controller: jeb.snahp.Apps.RequestManager.RequestManagerController:changeSolverWithUsername}
    requirements:
        topicId: \d+
        solverUsername: \w+
