parameters:
  jeb.snahp.giftbox:
    christmas_2019_bonus:
      items:
        completion_5:
          type: 'completion_5'
          description: '5 Days Completion'
          required: 5
          job_queue:
            giveaway_shatners:
              amount: 5000
              display_name: '5 Days Completion'
        completion_9:
          type: 'completion_9'
          description: '9 Days Completion'
          required: 9
          job_queue:
            giveaway_shatners:
              amount: 5000
              display_name: '9 Days Completion'
        completion_10:
          type: 'completion_10'
          description: '10 Days Completion'
          required: 10
          job_queue:
            giveaway_shatners:
              amount: 10000
              display_name: '10 Days Completion'
    christmas_2019:
      startDate: 1576368000
      endDate: 1577231999
      title: 'Happy Holidays.'
      items:
        common:
          type: 'common'
          description: 'This is a common item.'
          probability: 1
          img_url: 'https://i.imgur.com/J3qRpHX.png'
          job_queue:
            giveaway_shatners:
              amount: 1000
              display_name: 'Common Item'
        uncommon:
          type: 'uncommon'
          description: 'This is a uncommon item.'
          probability: 3
          img_url: 'https://i.imgur.com/3UDxPoB.jpg'
          job_queue:
            giveaway_shatners:
              amount: 2000
              display_name: 'Uncommon Item'
        rare:
          type: 'rare'
          description: 'This is a rare item.'
          probability: 9
          img_url: 'https://i.imgur.com/h0jnljA.png'
          job_queue:
            giveaway_shatners:
              amount: 4000
              display_name: 'Rare Item'
        mythical:
          type: 'mythical'
          description: 'This is a mythical item.'
          probability: 100 
          img_url: 'https://i.imgur.com/uYaHsN9.png'
          job_queue:
            giveaway_shatners:
              amount: 20000
              display_name: 'Mythical Item'
        legendary:
          type: 'legendary'
          description: 'This is a legendary item.'
          probability: 2000
          img_url: 'https://i.imgur.com/xrPq4bs.jpg'
          job_queue:
            giveaway_custom_rank:
              display_name: 'Custom Rank - Legendary Item'
            giveaway_shatners:
              amount: 30000
              display_name: 'Legendary Item Bundle'
        immortal:
          type: 'immortal'
          description: 'This is an immortal item.'
          probability: 10000
          img_url: 'https://i.imgur.com/mG8JXFK.png'
          job_queue:
            giveaway_invites:
              amount: 1
              display_name: '1 Invitation Point - Immortal Item'
            giveaway_shatners:
              amount: 60000
              display_name: 'Immortal Item Bundle'
        arcana:
          type: 'arcana'
          description: 'This is a arcana item.'
          probability: 1000000
          img_url: 'https://i.imgur.com/J3s644u.png'
          job_queue:
            giveaway_arcana:
              display_name: 'Arcana Item'
