imports:
  # - { resource: 'mute_user/parameters.yml' }
services:
  jeb.snahp.MuteUserMCPController:
    class: jeb\snahp\Apps\MuteUser\MuteUserMCPController
    arguments:
      - '@dbal.conn'
      - '@user'
      - '@config'
      - '@request'
      - '@template'
      - '@service_container'
      - '@controller.helper'
      - '%jeb.snahp.tables%'
      - '@jeb.snahp.auth.user_auth'
      - '@jeb.snahp.MuteUserHelper'
  jeb.snahp.MuteUserListener: # EVENT LISTENER
    class: jeb\snahp\Apps\MuteUser\MuteUserListener
    arguments:
      - '@config'
      - '@user'
      - '@jeb.snahp.auth.user_auth'
    tags:
      - { name: event.listener }
  jeb.snahp.MuteUserHelper: # HELPER
    class: jeb\snahp\Apps\MuteUser\MuteUserHelper
    arguments:
      - '@dbal.conn'
      - '@user'
      - '%jeb.snahp.tables%'
      - '@jeb.snahp.auth.user_auth'
