##########
#  VIEW  #
##########

jeb.snahp.routing.xmas.distriutor.distribute_invites:
    path: /snahp/xmas/distributor/distribute-invites
    defaults: { _controller: jeb.snahp.Apps.Xmas.XmasPrizeDistributorController:distributeInvites}

jeb.snahp.routing.xmas.distriutor.distribute:
    path: /snahp/xmas/distributor/distribute/{start}
    defaults: { _controller: jeb.snahp.Apps.Xmas.XmasPrizeDistributorController:distribute}
    requirements:
        start: \d+

jeb.snahp.routing.xmas.distriutor.distribute_quest_prizes:
    path: /snahp/xmas/distributor/distribute-quest
    defaults: { _controller: jeb.snahp.Apps.Xmas.XmasPrizeDistributorController:distributeQuestPrizes}


jeb.snahp.routing.xmas.summary:
    path: /snahp/xmas/summary
    defaults: { _controller: jeb.snahp.Apps.Xmas.XmasController:summary}

jeb.snahp.routing.xmas.create_boards:
    # Simulate mass creation of board
    path: /snahp/xmas/create-boards
    defaults: { _controller: jeb.snahp.Apps.Xmas.XmasController:simulateCreate}

jeb.snahp.routing.xmas.simulate_votes:
    # Simulate mass voting
    path: /snahp/xmas/simulate-votes
    defaults: { _controller: jeb.snahp.Apps.Xmas.XmasController:simulateVotes}

jeb.snahp.routing.xmas.simulate_votes_period:
    # Simulate mass voting
    path: /snahp/xmas/simulate-votes/{period}
    defaults: { _controller: jeb.snahp.Apps.Xmas.XmasController:simulateVotesPeriod}
    requirements:
        period: \d+

jeb.snahp.routing.xmas.score:
    # Score All Boards
    path: /snahp/xmas/score
    defaults: { _controller: jeb.snahp.Apps.Xmas.XmasController:score}

jeb.snahp.routing.xmas.reset_timer:
    # Score All Boards
    path: /snahp/xmas/reset-timer/{mode}
    defaults: { _controller: jeb.snahp.Apps.Xmas.XmasController:resetTimer}
    requirements:
        mode: \d+


##############
#  API VIEW  #
##############


# jeb.snahp.routing.xmas.list_board:
#     path: /snahp/xmas/board
#     defaults: { _controller: jeb.snahp.Apps.Xmas.BoardListCreateAPIView:dispatch}
# jeb.snahp.routing.xmas.retrieve_board:
#     path: /snahp/xmas/board/{id}
#     defaults: { _controller: jeb.snahp.Apps.Xmas.BoardRetrieveUpdateDestroyAPIView:dispatch}
#     requirements:
#         id: \d+
#
jeb.snahp.routing.xmas.list_vote:
    path: /snahp/xmas/vote
    defaults: { _controller: jeb.snahp.Apps.Xmas.VoteListCreateAPIView:dispatch}
# jeb.snahp.routing.xmas.retrieve_vote:
#     path: /snahp/xmas/vote/{id}
#     defaults: { _controller: jeb.snahp.Apps.Xmas.VoteRetrieveUpdateDestroyAPIView:dispatch}
#     requirements:
#         id: \d+


####################
#  Setup Database  #
####################


jeb.snahp.routing.Xmas.setup_database:
    path: /snahp/xmas/init
    defaults: { _controller: jeb.snahp.Apps.Xmas.SetupDatabaseView:view}
