jeb_snahp_routing.mass_indexer.user:
    path: /snahp/mass-indexer/unindex-user/{username}
    defaults: { _controller: jeb.snahp.MassIndexerController:unindexUser}
    requirements:
        username: \S+
jeb_snahp_routing.mass_indexer.topic:
    path: /snahp/mass-indexer/unindex-topic/{topicId}
    defaults: { _controller: jeb.snahp.MassIndexerController:unindexTopic}
    requirements:
        topidIc: \d+
jeb.snahp.routing.mass_indexer.forum:
    path: /snahp/mass-indexer/unindex-forum/{forumId}
    defaults: { _controller: jeb.snahp.MassIndexerController:unindexForum}
    requirements:
        topidIc: \d+
jeb.snahp.routing.mass_indexer.graveyard:
    path: /snahp/mass-indexer/unindex-graveyard
    defaults: { _controller: jeb.snahp.MassIndexerController:unindexGraveyard}
