jeb_snahp_economy.product_class_editor:
    path: /snahp/economy/pce/{mode}/
    defaults: { _controller: jeb.snahp.product_class_editor:handle}
    requirements:
        mode: \S+
jeb_snahp_economy.economy_user_dashboard:
    path: /snahp/economy/dashboard/{mode}/
    defaults: { _controller: jeb.snahp.economy_user_dashboard:handle}
    requirements:
        mode: \S+
jeb_snahp_economy.economy_dashboard:
    path: /snahp/economy/mcp/dashboard/{mode}/
    defaults: { _controller: jeb.snahp.economy_dashboard:handle}
    requirements:
        mode: \S+
jeb_snahp_economy.user_account_manager:
    path: /snahp/economy/uam/{mode}/
    defaults: { _controller: jeb.snahp.user_account_manager:handle}
    requirements:
        mode: \S+
jeb_snahp_economy.economy_init:
    path: /snahp/economy/economy_init/{mode}/
    defaults: { _controller: jeb.snahp.economy_init:handle}
    requirements:
        mode: \S+
