jeb_snahp_wiki.wiki:
    path: /snahp/wiki/{mode}/
    defaults: { _controller: jeb.snahp.wiki:handle}
    requirements:
        mode: \S+
jeb_snahp_wiki.editor:
    path: /snahp/wiki_editor/{mode}/
    defaults: { _controller: jeb.snahp.wiki:handle_editor}
    requirements:
        mode: \S+
