services:
  jeb.snahp.theme_switch: # CONTROLLER
    class: jeb\snahp\controller\theme_switch\theme_switch
    arguments:
      - '@dbal.conn'
      - '@user'
      - '@config'
      - '@request'
      - '@template'
      - '@service_container'
      - '@controller.helper'
      - '%jeb.snahp.tables%'
      - '@jeb.snahp.auth.user_auth'
