##########
#  VIEW  #
##########


jeb.snahp.routing.boilerplate_.main:
    path: /snahp/boilerplate-
    defaults: { _controller: jeb.snahp.Apps.Boilerplate.BoilerplateController:view}


##############
#  API VIEW  #
##############


jeb.snahp.routing.boilerplate_.list_modelname_:
    path: /snahp/boilerplate-/modelname-
    defaults: { _controller: jeb.snahp.Apps.Boilerplate.ModelNameListCreateAPIView:dispatch}
jeb.snahp.routing.boilerplate_.retrieve_modelname_:
    path: /snahp/boilerplate-/modelname-/{id}
    defaults: { _controller: jeb.snahp.Apps.Boilerplate.ModelNameRetrieveUpdateDestroyAPIView:dispatch}
    requirements:
        id: \d+
