jeb_snahp_routing.boilerplate.retrieve:
    path: /snahp/boilerplate/{id}
    defaults: { _controller: jeb.snahp.BoilerplateController:retrieveView}
    requirements:
        id: \d+
jeb_snahp_routing.boilerplate.list:
    path: /snahp/boilerplate
    defaults: { _controller: jeb.snahp.BoilerplateController:createListView}
