##########
#  VIEW  #
##########


jeb.snahp.routing.boilerplate.main:
    path: /snahp/boilerplate
    defaults: { _controller: jeb.snahp.Apps.Boilerplate.BoilerplateController:view}


##############
#  API VIEW  #
##############


jeb.snahp.routing.boilerplate.list_model_name:
    path: /snahp/boilerplate/model-name
    defaults: { _controller: jeb.snahp.Apps.Boilerplate.ModelNameListCreateAPIView:dispatch}
jeb.snahp.routing.boilerplate.retrieve_model_name:
    path: /snahp/boilerplate/model-name/{id}
    defaults: { _controller: jeb.snahp.Apps.Boilerplate.ModelNameRetrieveUpdateDestroyAPIView:dispatch}
    requirements:
        id: \d+
