jeb.snahp.routing.boilerplate.retrieve:
    path: /snahp/boilerplate/{id}
    defaults: { _controller: jeb.snahp.Apps.Boilerplate.BoilerplateController:retrieveView}
    requirements:
        id: \d+
jeb.snahp.routing.boilerplate.list:
    path: /snahp/boilerplate
    defaults: { _controller: jeb.snahp.Apps.Boilerplate.BoilerplateController:createListView}
