# imports:
#     - { resource: 'dir/parameters.yml' }
services:

##########
#  View  #
##########

    jeb.snahp.Apps.Boilerplate.BoilerplateController:
        class: jeb\snahp\Apps\Boilerplate\BoilerplateController
        arguments:
            - @dbal.conn
            - @user
            - @config
            - @request
            - @template
            - @service_container
            - @controller.helper
            - %jeb.snahp.tables%
            - @jeb.snahp.auth.user_auth
            - @jeb.snahp.Apps.Boilerplate.BoilerplateHelper

##############
#  API VIEW  #
##############

    jeb.snahp.Apps.Boilerplate.ModelNameListCreateAPIView:
        class: jeb\snahp\Apps\Boilerplate\ModelNameListCreateAPIView
        arguments:
            - @request
            - @jeb.snahp.auth.user_auth
            - @jeb.snahp.Apps.Boilerplate.Models.ModelName
    jeb.snahp.Apps.Boilerplate.ModelNameRetrieveUpdateDestroyAPIView:
        class: jeb\snahp\Apps\Boilerplate\ModelNameRetrieveUpdateDestroyAPIView
        arguments:
            - @request
            - @jeb.snahp.auth.user_auth
            - @jeb.snahp.Apps.Boilerplate.Models.ModelName


############
#  HELPER  #
############


    jeb.snahp.Apps.Boilerplate.BoilerplateHelper:
        class: jeb\snahp\Apps\Boilerplate\BoilerplateHelper
        arguments:
            - @dbal.conn
            - @user
            - @template
            - %jeb.snahp.tables%
            - @jeb.snahp.auth.user_auth


###########
#  MODEL  #
###########


    jeb.snahp.Apps.Boilerplate.Models.ModelName:
        class: jeb\snahp\Apps\Boilerplate\Models\ModelName


####################
#  EVENT LISTENER  #
####################


    jeb.snahp.Apps.Boilerplate.BoilerplateEventListener:
        class: jeb\snahp\Apps\Boilerplate\BoilerplateEventListener
        arguments:
            - @user
            - @config
            - @jeb.snahp.auth.user_auth
            - @jeb.snahp.Apps.Boilerplate.BoilerplateHelper
        tags:
            - { name: event.listener }
