services:

##########
#  View  #
##########

    jeb.snahp.Apps.InviteTree.InviteTreeController:
        class: jeb\snahp\Apps\InviteTree\InviteTreeController
        arguments:
            - "@dbal.conn"
            - "@user"
            - "@config"
            - "@request"
            - "@template"
            - "@service_container"
            - "@controller.helper"
            - "%jeb.snahp.tables%"
            - "@jeb.snahp.auth.user_auth"
            - "@jeb.snahp.Apps.InviteTree.InviteTreeHelper"


############
#  HELPER  #
############


    jeb.snahp.Apps.InviteTree.InviteTreeHelper:
        class: jeb\snahp\Apps\InviteTree\InviteTreeHelper
        arguments:
            - "@dbal.conn"
            - "%jeb.snahp.tables%"
            - "@jeb.snahp.auth.user_auth"
            - "@jeb.snahp.Apps.Core.Pagination.LimitOffsetPagination"
            - "@jeb.snahp.Apps.Core.Db.QuerySetFactory"
