services:

##########
#  View  #
##########

    jeb.snahp.Apps.Toplist.ToplistController:
        class: jeb\snahp\Apps\Toplist\ToplistController
        arguments:
            - "@jeb.snahp.auth.user_auth"
            - "@jeb.snahp.Apps.Toplist.ToplistHelper"


############
#  HELPER  #
############


    jeb.snahp.Apps.Toplist.ToplistHelper:
        class: jeb\snahp\Apps\Toplist\ToplistHelper
        arguments:
            - "@dbal.conn"
            - "@config_text"
            - "@jeb.snahp.auth.user_auth"
            - "@jeb.snahp.Apps.Core.Db.QuerySetFactory"


####################
#  EVENT LISTENER  #
####################


    jeb.snahp.Apps.Toplist.ToplistEventListener:
        class: jeb\snahp\Apps\Toplist\ToplistEventListener
        arguments:
            - "@config"
            - "@template"
            - "@jeb.snahp.auth.user_auth"
            - "@jeb.snahp.Apps.Toplist.ToplistHelper"
        tags:
            - { name: event.listener }
