services:
    jeb.snahp.database_manager:
        class: jeb\snahp\controller\database_manager\database_manager
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@config'
            - '@request'
            - '@template'
            - '@service_container'
            - '@controller.helper'
            - '%jeb.snahp.tables%'
            - '@jeb.snahp.auth.user_auth'
