parameters:
    jeb.snahp.emotes:
        # yuta1
        e_aa000:
            url: 'https://i.imgur.com/SWuKC6Z.gif'
            type: 0
        e_aa001:
            url: 'https://i.imgur.com/I1bQd6m.gif'
            type: 0
        e_aa002:
            url: 'https://i.imgur.com/4oshMlG.gif'
            type: 0
        e_aa003:
            url: 'https://i.imgur.com/pqiVOzx.gif'
            type: 0
        e_aa004:
            url: 'https://i.imgur.com/tD0i6t8.gif'
            type: 0
        e_aa005:
            url: 'https://i.imgur.com/fRGuJEH.gif'
            type: 0
        e_aa006:
            url: 'https://i.imgur.com/8miVRVN.gif'
            type: 0
        e_aa007:
            url: 'https://i.imgur.com/L8rAjGl.gif'
            type: 0
        e_aa008:
            url: 'https://i.imgur.com/FfnfqFL.gif'
            type: 0

        # yuta2
        e_aa100:
            url: 'https://i.imgur.com/85va7sR.gif'
            type: 0
        e_aa101:
            url: 'https://i.imgur.com/TIf8IJF.gif'
            type: 0
        e_aa102:
            url: 'https://i.imgur.com/tYfczLA.gif'
            type: 0
        e_aa103:
            url: 'https://i.imgur.com/H0v81pR.gif'
            type: 0
        e_aa104:
            url: 'https://i.imgur.com/nuTSN3E.gif'
            type: 0
        e_aa105:
            url: 'https://i.imgur.com/vsDN0EB.gif'
            type: 0
        e_aa106:
            url: 'https://i.imgur.com/JnbUH2a.gif'
            type: 1
        e_aa107:
            url: 'https://i.imgur.com/mEhJWhi.gif'
            type: 1
        e_aa108:
            url: 'https://i.imgur.com/rdwYBjo.gif'
            type: 1
        e_aa109:
            url: 'https://i.imgur.com/KxSjcUi.gif'
            type: 1
        e_aa110:
            url: 'https://i.imgur.com/8uPlzce.gif'
            type: 1

        # tobi1
        e_ab000:
            url: 'https://i.imgur.com/tGdABP9.gif'
            type: 0
        e_ab001:
            url: 'https://i.imgur.com/GjM7IKA.gif'
            type: 0
        e_ab002:
            url: 'https://i.imgur.com/UEGW8LB.gif'
            type: 0
        e_ab003:
            url: 'https://i.imgur.com/IQZJcjp.gif'
            type: 0
        e_ab004:
            url: 'https://i.imgur.com/DPJiOka.gif'
            type: 0
        e_ab005:
            url: 'https://i.imgur.com/hTf3WvO.gif'
            type: 0
        e_ab006:
            url: 'https://i.imgur.com/SSPg3uP.gif'
            type: 0
        e_ab007:
            url: 'https://i.imgur.com/Mf6rHVR.gif'
            type: 0
        e_ab008:
            url: 'https://i.imgur.com/oPkXrde.gif'
            type: 0

        # tobi2
        e_ab100:
            url: 'https://i.imgur.com/ja3dMi7.gif'
            type: 0
        e_ab101:
            url: 'https://i.imgur.com/eitYFXF.gif'
            type: 0
        e_ab102:
            url: 'https://i.imgur.com/3NMuuJu.gif'
            type: 0
        e_ab103:
            url: 'https://i.imgur.com/CMLlN5O.gif'
            type: 1
        e_ab104:
            url: 'https://i.imgur.com/Nmv839o.gif'
            type: 1
        e_ab105:
            url: 'https://i.imgur.com/6WxPJJB.gif'
            type: 1
        e_ab106:
            url: 'https://i.imgur.com/OWD0Inh.gif'
            type: 1
        e_ab107:
            url: 'https://i.imgur.com/wJpv1yL.gif'
            type: 1

        # friends1
        e_ac000:
            url: 'https://i.imgur.com/V9urSJI.gif'
            type: 0
        e_ac001:
            url: 'https://i.imgur.com/T0EYtQX.gif'
            type: 0
        e_ac002:
            url: 'https://i.imgur.com/Qvt9QLo.gif'
            type: 0
        e_ac003:
            url: 'https://i.imgur.com/Ryr6G5F.gif'
            type: 0
        e_ac004:
            url: 'https://i.imgur.com/HAbrkRf.gif'
            type: 0
        e_ac005:
            url: 'https://i.imgur.com/U3P59Mv.gif'
            type: 0
        e_ac006:
            url: 'https://i.imgur.com/hVcMylU.gif'
            type: 0
        e_ac007:
            url: 'https://i.imgur.com/WZIdxc0.gif'
            type: 0

        # twitch1
        e_tw000:
            url: 'https://i.imgur.com/IHmm9Qs.png'
            type: 0
            css: 'twitch_50'
        e_tw001:
            url: 'https://i.imgur.com/nAqPDjL.png'
            type: 0
            css: 'twitch_50'
        e_tw002:
            url: 'https://i.imgur.com/ClWGLwV.png'
            type: 0
            css: 'twitch_50'
        e_tw003: &e_tw003
            url: 'https://i.imgur.com/1Ol0hmq.png'
            type: 0
            css: 'discord_44'
            title: 'cry'

        # discord
        e_ds000: &e_ds000
            url: 'https://i.imgur.com/uENhb6d.png'
            type: 0
            css: 'discord_44'
            title: 'comfy'
        e_ds001: &e_ds001
            url: 'https://i.imgur.com/AdWBoza.png'
            type: 0
            css: 'discord_44'
            title: 'inspect'
        e_ds002: &e_ds002
            url: 'https://i.imgur.com/SlwxIdn.png'
            type: 0
            css: 'discord_44'
            title: 'smug'
        e_ds003: &e_ds003
            url: 'https://i.imgur.com/5bXpTQD.png'
            type: 0
            css: 'discord_44'
            title: 'lol'
        e_ds005: &e_ds005
            url: 'https://discordemoji.com/assets/emoji/6727_JigglyAngry.png'
            url: 'https://i.imgur.com/yyfBusD.png'
            type: 0
            css: 'discord_44'
            title: 'angry'
        e_ds004: &e_ds004
            url: 'https://i.imgur.com/96mAOWK.gif'
            type: 0
            css: 'discord_44'
            title: 'nom'

        # Seasonals: Thanksgiving
        e_th001:
            url: 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/google/223/turkey_1f983.png'
            type: 0
            title: 'Turkey Day!'

        # common alias
        e_comfy: *e_ds000
        e_inspect: *e_ds001
        e_smug: *e_ds002
        e_lol: *e_ds003
        e_nom: *e_ds004
        e_cry: *e_tw003
        e_angry: *e_ds005
