parameters:
    jeb.snahp.emotes:
        e_aa000:
            url: 'https://i.imgur.com/SWuKC6Z.gif'
            type: 0
        e_aa001:
            url: 'https://i.imgur.com/I1bQd6m.gif'
            type: 0
        e_aa002:
            url: 'https://i.imgur.com/4oshMlG.gif'
            type: 0
        e_aa003:
            url: 'https://i.imgur.com/pqiVOzx.gif'
            type: 0
        e_aa004:
            url: 'https://i.imgur.com/tD0i6t8.gif'
            type: 0
        e_aa005:
            url: 'https://i.imgur.com/fRGuJEH.gif'
            type: 0
        e_aa006:
            url: 'https://i.imgur.com/8miVRVN.gif'
            type: 0
        e_aa007:
            url: 'https://i.imgur.com/L8rAjGl.gif'
            type: 0
        e_aa008:
            url: 'https://i.imgur.com/FfnfqFL.gif'
            type: 0

        e_ab000:
            url: 'https://i.imgur.com/tGdABP9.gif'
            type: 1
        e_ab001:
            url: 'https://i.imgur.com/GjM7IKA.gif'
            type: 1
        e_ab002:
            url: 'https://i.imgur.com/UEGW8LB.gif'
            type: 1
        e_ab003:
            url: 'https://i.imgur.com/IQZJcjp.gif'
            type: 1
        e_ab004:
            url: 'https://i.imgur.com/DPJiOka.gif'
            type: 1
        e_ab005:
            url: 'https://i.imgur.com/hTf3WvO.gif'
            type: 1
        e_ab006:
            url: 'https://i.imgur.com/SSPg3uP.gif'
            type: 1
        e_ab007:
            url: 'https://i.imgur.com/Mf6rHVR.gif'
            type: 1
        e_ab008:
            url: 'https://i.imgur.com/oPkXrde.gif'
            type: 1

