parameters:
    jeb.snahp.tables.snp_table: '%core.table_prefix%snp_table'
    jeb.snahp.tables: 
        req:    '%core.table_prefix%snahp_request'
        requsr: '%core.table_prefix%snahp_request_users'
        dibs:   '%core.table_prefix%snahp_dibs'
        bump_topic: '%core.table_prefix%snahp_bump_topic'
        invite: '%core.table_prefix%snahp_invite'
        invite_users: '%core.table_prefix%snahp_invite_users'
        thanks: '%core.table_prefix%thanks'
        manual_search_posts: '%core.table_prefix%snahp_manual_search_posts'
    jeb.snahp.bump_topic:
        def:
            enable: 1
            disable: 9
    jeb.snahp.req:
        def:
            open: 1
            solve: 2
            dib: 3
            fulfill: 4
            undib: 5
            graveyard: 8
            terminate: 9
            deleted: 19
            set:
                graveyardable:
                    - 2
                    - 9
                closed:
                    - 2
                    - 9
                    - 19
                open:
                    - 1
                    - 3
                    - 4
                    - 5
    jeb.snahp.reqsmcp:
        def:
            disable: 9
            enable: 1

