imports:
    - { resource: 'tables.yml' }
    - { resource: 'groups.yml' }
    - { resource: 'emotes.yml' }
    - { resource: 'achievements.yml' }

parameters:

    jeb.snahp.bump_topic:
        def:
            enable: 1
            disable: 9

    jeb.snahp.tags:
        encode:
            # Only key is being used in the base.php->encode_tags. Value
            # is irrelevant
            request: 1
            accepted: 2
            fulfilled: 3
            solved: 4
            closed: 5
            mega: 6
            zippy: 7
            gdrive: 8
            android: 9
            ios: 10 
            win: 11
            pc: 12
            mac: 13
            updating: &updating 14
            ongoing: *updating
        decode:
            default:
                request:   '<span class="btn open">R</span>'
                accepted:  '<span class="btn dib">A</span>'
                fulfilled: '<span class="btn fulfill">F</span>'
                solved:    '<span class="btn solve">S</span>'
                closed:    '<span class="btn terminate">C</span>'
                mega:      '<img class="mega_icon" src="https://i.imgur.com/w5aP33F.png" title="mega">'
                zippy:     '<img class="zippy_icon" src="https://i.imgur.com/qD95AzT.png" title="zippy">'
                gdrive:    '<img class="gdrive_icon" src="https://i.imgur.com/VQv2dUm.png" title="gdrive">'
                android:   '<img class="android_icon" src="https://i.imgur.com/tDL6Rl5.png" title="android">'
                ios:       '<img class="ios_icon" src="https://i.imgur.com/kjBQJhi.png" title="ios">'
                mac:       '<img class="ios_icon" src="https://i.imgur.com/kjBQJhi.png" title="mac">'
                win:       '<img class="ios_icon" src="https://i.imgur.com/6DQqf6m.png" title="win">'
                updating: &updating '<img class="ios_icon" src="https://i.imgur.com/rgplXx8.png" title="updating">'
                ongoing: *updating
            small:
                request:   '<span class="small_host_icon"><span class="btn open">R</span></span>'
                solved:    '<span class="small_host_icon"><span class="btn solve">S</span></span>'
                accepted:  '<span class="small_host_icon"><span class="btn dib">A</span></span>'
                fulfilled: '<span class="small_host_icon"><span class="btn fulfill">F</span></span>'
                closed:    '<span class="small_host_icon"><span class="btn terminate">C</span></span>'
                mega:      '<span class="small_host_icon"><img class="mega_icon" src="https://i.imgur.com/w5aP33F.png" title="mega"></span>'
                zippy:     '<span class="small_host_icon"><img class="zippy_icon" src="https://i.imgur.com/qD95AzT.png" title="zippy"></span>'
                gdrive:    '<span class="small_host_icon"><img class="gdrive_icon" src="https://i.imgur.com/VQv2dUm.png" title="gdrive"></span>'
                android:   '<span class="small_host_icon"><img class="android_icon" src="https://i.imgur.com/tDL6Rl5.png" title="android"></span>'
                ios:       '<span class="small_host_icon"><img class="ios_icon" src="https://i.imgur.com/kjBQJhi.png" title="ios"></span>'
                mac:       '<span class="small_host_icon"><img class="ios_icon" src="https://i.imgur.com/kjBQJhi.png" title="mac"></span>'
                win:       '<span class="small_host_icon"><img class="ios_icon" src="https://i.imgur.com/6DQqf6m.png" title="win"></span>'
                updating: &updating '<span class="small_host_icon"><img class="ios_icon" src="https://i.imgur.com/rgplXx8.png" title="updating"></span>'
                ongoing: *updating

    jeb.snahp.req:
        def:
            open: 1
            solve: 2
            dib: 3
            fulfill: 4
            undib: 5
            graveyard: 8
            terminate: 9
            deleted: 19
            set:
                graveyardable:
                    - 2
                    - 9
                closed:
                    - 2
                    - 9
                    - 19
                open:
                    - 1
                    - 3
                    - 4
                    - 5

    jeb.snahp.reqsmcp:
        def:
            disable: 9
            enable: 1

    jeb.snahp.fav:
        dev:
            img:
                50: 'https://i.imgur.com/m6XofFz.png'  # Imported
                51: 'https://i.imgur.com/7hjHY25.png'  # Apps
                52: 'https://i.imgur.com/YBPkBaX.png'  # Games
                53: 'https://i.imgur.com/i9pIvNy.png'  # TV Shows
                54: 'https://i.imgur.com/RKQJ9Vl.png'  # Music
                55: 'https://i.imgur.com/w8Tmnyk.png'  # Anime
                56: 'https://i.imgur.com/X4OIR7c.png'  # Miscellaneous
                57: 'https://i.imgur.com/OU5XZDq.png'  # Developmental Resources
                82: 'https://i.imgur.com/pK0D79T.png'  # Movies
                74: 'https://i.imgur.com/Z1NwGH5.png'  # Manga
                75: 'https://i.imgur.com/YtWaxUg.png'  # ebooks
                105: 'https://i.imgur.com/IHNXV9h.png' # sports
                59: 'https://i.imgur.com/FszcDV4.png'  # Apps PC
                106: 'https://i.imgur.com/FPEhkvf.png' # Misc Comics
                65: 'https://i.imgur.com/YBPkBaX.png'  # Games Console
        production:
            img:
                27: 'https://i.imgur.com/m6XofFz.png' # Imported
                9:  'https://i.imgur.com/7hjHY25.png' # Apps
                10: 'https://i.imgur.com/YBPkBaX.png' # Games
                12: 'https://i.imgur.com/i9pIvNy.png' # TV Shows
                14: 'https://i.imgur.com/RKQJ9Vl.png' # Music
                13: 'https://i.imgur.com/w8Tmnyk.png' # Anime
                15: 'https://i.imgur.com/X4OIR7c.png' # Miscellaneous
                76: 'https://i.imgur.com/OU5XZDq.png' # Developmental Resources
                11: 'https://i.imgur.com/pK0D79T.png' # Movies
                60: 'https://i.imgur.com/Z1NwGH5.png' # Manga
                37: 'https://i.imgur.com/YtWaxUg.png' # ebooks
                61: 'https://i.imgur.com/IHNXV9h.png' # sports
                40: 'https://i.imgur.com/FszcDV4.png' # Apps PC
                43: 'https://i.imgur.com/FPEhkvf.png' # Misc Comics
                25: 'https://i.imgur.com/YBPkBaX.png' # Games Console

