parameters:
    jeb.snahp.tables.snp_table: '%core.table_prefix%snp_table'
    jeb.snahp.tables: 
        req:    '%core.table_prefix%snahp_request'
        requsr: '%core.table_prefix%snahp_request_users'
        dibs:   '%core.table_prefix%snahp_dibs'
        bump_topic: '%core.table_prefix%snahp_bump_topic'
        invite: '%core.table_prefix%snahp_invite'
        invite_users: '%core.table_prefix%snahp_invite_users'
        thanks: '%core.table_prefix%thanks'
        tpl: '%core.table_prefix%snahp_tpl'
        manual_search_posts: '%core.table_prefix%snahp_manual_search_posts'
    jeb.snahp.bump_topic:
        def:
            enable: 1
            disable: 9
    jeb.snahp.tags:
        encode:
            request: 1
            accepted: 2
            fulfilled: 3
            solved: 4
            closed: 5
            mega: 6
            zippy: 7
            gdrive: 8
            android: 9
            ios: 10 
        decode:
            default:
                request:   '<span class="btn open">R</span>'
                accepted:  '<span class="btn dib">A</span>'
                fulfilled: '<span class="btn fulfill">F</span>'
                solved:    '<span class="btn solve">S</span>'
                closed:    '<span class="btn terminate">C</span>'
                mega:      '<img class="mega_icon" src="https://i.imgur.com/w5aP33F.png">'
                zippy:     '<img class="zippy_icon" src="https://i.imgur.com/qD95AzT.png">'
                gdrive:    '<img class="gdrive_icon" src="https://i.imgur.com/VQv2dUm.png">'
                android:   '<img class="android_icon" src="https://i.imgur.com/tDL6Rl5.png">'
                ios:       '<img class="ios_icon" src="https://i.imgur.com/kjBQJhi.png">'
            small:
                request:   '<span class="small"><span class="btn open">R</span></span>'
                solved:    '<span class="small"><span class="btn solve">S</span></span>'
                accepted:  '<span class="small"><span class="btn dib">A</span></span>'
                fulfilled: '<span class="small"><span class="btn fulfill">F</span></span>'
                closed:    '<span class="small"><span class="btn terminate">C</span></span>'
                mega:      '<span class="small"><img class="mega_icon" src="https://i.imgur.com/w5aP33F.png"></span>'
                zippy:     '<span class="small"><img class="zippy_icon" src="https://i.imgur.com/qD95AzT.png"></span>'
                gdrive:    '<span class="small"><img class="gdrive_icon" src="https://i.imgur.com/VQv2dUm.png"></span>'
                android:   '<span class="small"><img class="android_icon" src="https://i.imgur.com/tDL6Rl5.png"></span>'
                ios:       '<span class="small"><img class="ios_icon" src="https://i.imgur.com/kjBQJhi.png"></span>'
    jeb.snahp.req:
        def:
            open: 1
            solve: 2
            dib: 3
            fulfill: 4
            undib: 5
            graveyard: 8
            terminate: 9
            deleted: 19
            set:
                graveyardable:
                    - 2
                    - 9
                closed:
                    - 2
                    - 9
                    - 19
                open:
                    - 1
                    - 3
                    - 4
                    - 5
    jeb.snahp.reqsmcp:
        def:
            disable: 9
            enable: 1

