parameters:
    jeb.snahp.tables.snp_table: '%core.table_prefix%snp_table'

    jeb.snahp.tables: 
        req:    '%core.table_prefix%snahp_request'
        requsr: '%core.table_prefix%snahp_request_users'
        dibs:   '%core.table_prefix%snahp_dibs'
        bump_topic: '%core.table_prefix%snahp_bump_topic'
        invite: '%core.table_prefix%snahp_invite'
        invite_users: '%core.table_prefix%snahp_invite_users'
        thanks: '%core.table_prefix%thanks'
        tpl: '%core.table_prefix%snahp_tpl'
        manual_search_posts: '%core.table_prefix%snahp_manual_search_posts'
        digg_slave: '%core.table_prefix%snahp_digg_slave'
        digg_master: '%core.table_prefix%snahp_digg_master'
        achievements: '%core.table_prefix%snahp_achievements'

    jeb.snahp.bump_topic:
        def:
            enable: 1
            disable: 9

    jeb.snahp.tags:
        encode:
            request: 1
            accepted: 2
            fulfilled: 3
            solved: 4
            closed: 5
            mega: 6
            zippy: 7
            gdrive: 8
            android: 9
            ios: 10 
        decode:
            default:
                request:   '<span class="btn open">R</span>'
                accepted:  '<span class="btn dib">A</span>'
                fulfilled: '<span class="btn fulfill">F</span>'
                solved:    '<span class="btn solve">S</span>'
                closed:    '<span class="btn terminate">C</span>'
                mega:      '<img class="mega_icon" src="https://i.imgur.com/w5aP33F.png">'
                zippy:     '<img class="zippy_icon" src="https://i.imgur.com/qD95AzT.png">'
                gdrive:    '<img class="gdrive_icon" src="https://i.imgur.com/VQv2dUm.png">'
                android:   '<img class="android_icon" src="https://i.imgur.com/tDL6Rl5.png">'
                ios:       '<img class="ios_icon" src="https://i.imgur.com/kjBQJhi.png">'
            small:
                request:   '<span class="small_host_icon"><span class="btn open">R</span></span>'
                solved:    '<span class="small_host_icon"><span class="btn solve">S</span></span>'
                accepted:  '<span class="small_host_icon"><span class="btn dib">A</span></span>'
                fulfilled: '<span class="small_host_icon"><span class="btn fulfill">F</span></span>'
                closed:    '<span class="small_host_icon"><span class="btn terminate">C</span></span>'
                mega:      '<span class="small_host_icon"><img class="mega_icon" src="https://i.imgur.com/w5aP33F.png"></span>'
                zippy:     '<span class="small_host_icon"><img class="zippy_icon" src="https://i.imgur.com/qD95AzT.png"></span>'
                gdrive:    '<span class="small_host_icon"><img class="gdrive_icon" src="https://i.imgur.com/VQv2dUm.png"></span>'
                android:   '<span class="small_host_icon"><img class="android_icon" src="https://i.imgur.com/tDL6Rl5.png"></span>'
                ios:       '<span class="small_host_icon"><img class="ios_icon" src="https://i.imgur.com/kjBQJhi.png"></span>'

    jeb.snahp.req:
        def:
            open: 1
            solve: 2
            dib: 3
            fulfill: 4
            undib: 5
            graveyard: 8
            terminate: 9
            deleted: 19
            set:
                graveyardable:
                    - 2
                    - 9
                closed:
                    - 2
                    - 9
                    - 19
                open:
                    - 1
                    - 3
                    - 4
                    - 5

    jeb.snahp.reqsmcp:
        def:
            disable: 9
            enable: 1

    jeb.snahp.fav:
        dev:
            img:
                50: 'https://i.imgur.com/m6XofFz.png'  # Imported
                51: 'https://i.imgur.com/7hjHY25.png'  # Apps
                52: 'https://i.imgur.com/YBPkBaX.png'  # Games
                53: 'https://i.imgur.com/i9pIvNy.png'  # TV Shows
                54: 'https://i.imgur.com/RKQJ9Vl.png'  # Music
                55: 'https://i.imgur.com/w8Tmnyk.png'  # Anime
                56: 'https://i.imgur.com/X4OIR7c.png'  # Miscellaneous
                57: 'https://i.imgur.com/OU5XZDq.png'  # Developmental Resources
                82: 'https://i.imgur.com/pK0D79T.png'  # Movies
                74: 'https://i.imgur.com/Z1NwGH5.png'  # Manga
                75: 'https://i.imgur.com/YtWaxUg.png'  # ebooks
                105: 'https://i.imgur.com/IHNXV9h.png' # sports
                59: 'https://i.imgur.com/FszcDV4.png'  # Apps PC
                106: 'https://i.imgur.com/FPEhkvf.png' # Misc Comics
                65: 'https://i.imgur.com/YBPkBaX.png'  # Games Console
        production:
            img:
                27: 'https://i.imgur.com/m6XofFz.png' # Imported
                9:  'https://i.imgur.com/7hjHY25.png' # Apps
                10: 'https://i.imgur.com/YBPkBaX.png' # Games
                12: 'https://i.imgur.com/i9pIvNy.png' # TV Shows
                14: 'https://i.imgur.com/RKQJ9Vl.png' # Music
                13: 'https://i.imgur.com/w8Tmnyk.png' # Anime
                15: 'https://i.imgur.com/X4OIR7c.png' # Miscellaneous
                76: 'https://i.imgur.com/OU5XZDq.png' # Developmental Resources
                11: 'https://i.imgur.com/pK0D79T.png' # Movies
                60: 'https://i.imgur.com/Z1NwGH5.png' # Manga
                37: 'https://i.imgur.com/YtWaxUg.png' # ebooks
                61: 'https://i.imgur.com/IHNXV9h.png' # sports
                40: 'https://i.imgur.com/FszcDV4.png' # Apps PC
                43: 'https://i.imgur.com/FPEhkvf.png' # Misc Comics
                25: 'https://i.imgur.com/YBPkBaX.png' # Games Console

    jeb.snahp.avatar.achievements:
        gambler:
            name: 'Gambler'
            img:
                url:
                    prosilver: 'https://i.imgur.com/bwNL1cp.png'
                    Basic: 'https://i.imgur.com/bwNL1cp.png'
                    Hexagon: 'https://i.imgur.com/esHx4Jt.png'
                    Acieeed!: 'https://i.imgur.com/LhiBN7O.png'
            title: "Gambler. {USERNAME} once went into a casino, casually rolled a 100, then left with bags o'cash."
            probability: 3
        thumb_raiser:
            name: 'Thumb Raiser'
            img:
                url:
                    prosilver: 'https://i.imgur.com/6ZKQIWN.png'
                    Basic: 'https://i.imgur.com/6ZKQIWN.png'
                    Hexagon: 'https://i.imgur.com/g0GgdaL.png'
                    Acieeed!: 'https://i.imgur.com/9sPuh9F.png'
            title: "Thumb Raiser. People everywhere raise their thumbs in {USERNAME}'s honor. No questions asked."
            probability: 20
        life_giver:
            name: 'Life Giver'
            img:
                url:
                    prosilver: 'https://i.imgur.com/Cpj3H7J.png'
                    Basic: 'https://i.imgur.com/Cpj3H7J.png'
                    Hexagon: 'https://i.imgur.com/VDYMGKY.png'
                    Acieeed!: 'https://i.imgur.com/b8671CB.png'
            title: "Life Giver. {USERNAME} breathes new life into every stranger he meets - one request at a time."
            probability: 25
        grave_digger:
            name: 'Grave Digger'
            img:
                url:
                    prosilver: 'https://i.imgur.com/c2AlUKM.png'
                    Basic: 'https://i.imgur.com/c2AlUKM.png'
                    Hexagon: 'https://i.imgur.com/qGrUH0v.png'
                    Acieeed!: 'https://i.imgur.com/gnccFDf.png'
            title: "Grave Digger. {USERNAME}'s peculiar habit of secretly digging through someone else's belongings has earned him this unceremonious title."
            probability: 5
        computer_whiz:
            name: 'Computer Whiz'
            img:
                url:
                    prosilver: 'https://i.imgur.com/BIts5ks.png'
                    Basic: 'https://i.imgur.com/BIts5ks.png'
                    Hexagon: 'https://i.imgur.com/dbTWs5M.png'
                    Acieeed!: 'https://i.imgur.com/QTD3GSu.png'
            title: "Computer Whiz. {USERNAME} has published more scholarly articles in the field of computer science than anyone else."
            probability: 20
        magnetic_personality:
            name: 'Magnetic Personality'
            img:
                url:
                    prosilver: 'https://i.imgur.com/NtvZyy4.png'
                    Basic: 'https://i.imgur.com/NtvZyy4.png'
                    Hexagon: 'https://i.imgur.com/SSOngus.png'
                    Acieeed!: 'https://i.imgur.com/VNCDFan.png'
            title: 'Magnetic Personality. Everyone diggs {USERNAME}!!! He is the most digged person on the planet.'
            probability: 20

