jeb_snahp_admin:
    path: /snahp/admin/
    defaults: { _controller: jeb.snahp.admin:handle}
jeb_snahp_reqs:
    path: /snahp/reqs/{fid}/{tid}/{pid}/{mode}/
    defaults: { _controller: jeb.snahp.reqs:handle}
    requirements:
        fid: \d+
        tid: \d+
        pid: \d+
        mode: \d+
jeb_snahp_reqsmcp:
    path: /snahp/reqsmcp/{mode}/{uid}/
    defaults: { _controller: jeb.snahp.reqs:handle_mcp}
    requirements:
        mode: \d+
        uid: \d+
jeb_snahp_acp_reqs_manage_user:
    path: /snahp/acp_reqs_manage_user/
    defaults: { _controller: jeb.snahp.acp_reqs:handle_manage_user}
    requirements:
jeb_snahp_acp_reqs_get_banned_dibbers:
    path: /snahp/acp_reqs_get_banned_dibbers/
    defaults: { _controller: jeb.snahp.acp_reqs:get_banned_dibbers}
jeb_snahp_acp_reqs_reset_user:
    path: /snahp/acp_reqs_reset_user/{username}/
    defaults: { _controller: jeb.snahp.acp_reqs:handle_reset_user}
    requirements:
        username: \S+
jeb_snahp_acp_reqs_userinfo:
    path: /snahp/acp_reqs_get_userinfo/{username}/
    defaults: { _controller: jeb.snahp.acp_reqs:get_userinfo}
    requirements:
        username: \S+
jeb_snahp_graveyard_request:
    path: /snahp/graveyard_request/
    defaults: { _controller: jeb.snahp.graveyard_request:handle}
# This is used for completely custom request form. Not implemented.
jeb_snahp_reqs_post:
    path: /snahp/reqs_post/{mode}/{fid}/
    defaults: { _controller: jeb.snahp.reqs_post:handle}
    requirements:
        mode: \S+
        fid: \d+
