routing_rh_tags:
    resource: 'routing/rh_tags.yml'
routing_test:
    resource: 'routing/test.yml'
routing_logger:
    resource: 'routing/logger.yml'
routing_wiki:
    resource: 'routing/wiki.yml'
routing_economy:
    resource: 'routing/economy.yml'
jeb_snahp_admin:
    path: /snahp/admin/
    defaults: { _controller: jeb.snahp.admin:handle}
jeb_snahp_mod_move_topic:
    path: /snahp/admin/move_topic/{tid}/{fid}/
    defaults: { _controller: jeb.snahp.admin:handle_move_single_topic}
    requirements:
        tid: \d+
        fid: \d+
jeb_snahp_acp_thanks:
    path: /snahp/acp_thanks/handle/{mode}/
    defaults: { _controller: jeb.snahp.acp_thanks:handle}
    requirements:
        mode: \S+
jeb_snahp_thanks:
    path: /snahp/thanks/handle/{mode}/
    defaults: { _controller: jeb.snahp.thanks:handle}
    requirements:
        mode: \S+
jeb_snahp_analytics:
    path: /snahp/analytics/handle/{mode}/
    defaults: { _controller: jeb.snahp.analytics:handle}
    requirements:
        mode: \S+
jeb_snahp_search_util:
    path: /snahp/search_util/{mode}/
    defaults: { _controller: jeb.snahp.search_util:handle}
    requirements:
        mode: \S+
jeb_snahp_acp_prune_users:
    path: /snahp/acp_prune_users/{mode}/
    defaults: { _controller: jeb.snahp.acp_prune_users:handle}
    requirements:
        mode: \S+
jeb_snahp_emotes:
    path: /snahp/emotes/{mode}/
    defaults: { _controller: jeb.snahp.emotes:handle}
    requirements:
        mode: \S+
jeb_snahp_cron:
    path: /snahp/cron/{mode}/
    defaults: { _controller: jeb.snahp.cron:handle}
    requirements:
        mode: \S+
jeb_snahp_help:
    path: /snahp/help/{mode}/
    defaults: { _controller: jeb.snahp.help:handle}
    requirements:
        mode: \S+
jeb_snahp_mdl:
    path: /snahp/mdl/{mode}/
    defaults: { _controller: jeb.snahp.mdl:handle}
    requirements:
        mode: \S+
jeb_snahp_reputation:
    path: /snahp/reputation/{mode}/
    defaults: { _controller: jeb.snahp.reputation:handle}
    requirements:
        mode: \S+
jeb_snahp_achievements:
    path: /snahp/achievements/{mode}/
    defaults: { _controller: jeb.snahp.achievements:handle}
    requirements:
        mode: \S+
jeb_snahp_custom_rank:
    path: /snahp/custom_rank/{mode}/
    defaults: { _controller: jeb.snahp.custom_rank:handle}
    requirements:
        mode: \S+
jeb_snahp_digg:
    path: /snahp/digg/{mode}/
    defaults: { _controller: jeb.snahp.digg:handle}
    requirements:
        mode: \S+
jeb_snahp_bank:
    path: /snahp/bank/{mode}/
    defaults: { _controller: jeb.snahp.bank:handle}
    requirements:
        mode: \S+
jeb_snahp_favorite:
    path: /snahp/favorite/{mode}/
    defaults: { _controller: jeb.snahp.favorite:handle}
    requirements:
        mode: \S+
jeb_snahp_userscript:
    path: /snahp/userscript/{mode}/
    defaults: { _controller: jeb.snahp.userscript:handle}
    requirements:
        mode: \S+
jeb_snahp_template:
    path: /snahp/template/{mode}/
    defaults: { _controller: jeb.snahp.template:handle}
    requirements:
        mode: \S+
jeb_snahp_invite:
    path: /snahp/invite/{mode}/
    defaults: { _controller: jeb.snahp.invite:handle}
    requirements:
        mode: \S+
jeb_snahp_reqs:
    path: /snahp/reqs/{fid}/{tid}/{pid}/{mode}/
    defaults: { _controller: jeb.snahp.reqs:handle}
    requirements:
        fid: \d+
        tid: \d+
        pid: \d+
        mode: \d+
jeb_snahp_reqs_my_request:
    path: /snahp/reqs/myrequests/
    defaults: { _controller: jeb.snahp.reqs:get_requests_as_json}
jeb_snahp_reqs_user_request:
    path: /snahp/reqs/myrequests/{username}/
    defaults: { _controller: jeb.snahp.reqs:get_requests_as_json}
    requirements:
        username: \S+
jeb_snahp_reqsmcp:
    path: /snahp/reqsmcp/{mode}/{uid}/
    defaults: { _controller: jeb.snahp.reqs:handle_mcp}
    requirements:
        mode: \d+
        uid: \d+
jeb_snahp_acp_fixmediainfo:
    path: /snahp/acp_fixmediainfo/{mode}/
    defaults: { _controller: jeb.snahp.acp_fixmediainfo:handle}
    requirements:
        mode: \S+
jeb_snahp_acp_fiximdb:
    path: /snahp/acp_fiximdb/{mode}/
    defaults: { _controller: jeb.snahp.acp_fiximdb:handle}
    requirements:
        mode: \S+
jeb_snahp_acp_invite:
    path: /snahp/acp_invite/{mode}/
    defaults: { _controller: jeb.snahp.acp_invite:handle}
    requirements:
        mode: \S+
jeb_snahp_acp_reqs_manage:
    path: /snahp/acp_reqs/manage/
    defaults: { _controller: jeb.snahp.acp_reqs:manage_requests}
jeb_snahp_acp_reqs_generate_statistics:
    path: /snahp/acp_reqs/generate_statistics/
    defaults: { _controller: jeb.snahp.acp_reqs:generate_statistics}
jeb_snahp_acp_reqs_resynch:
    path: /snahp/acp_reqs/resynch/
    defaults: { _controller: jeb.snahp.acp_reqs:resynchronize_requests}
jeb_snahp_acp_reqs_handle:
    path: /snahp/acp_reqs/handle/{mode}/
    defaults: { _controller: jeb.snahp.acp_reqs:handle}
    requirements:
        mode: \S+
jeb_snahp_acp_reqs_manage_user:
    path: /snahp/acp_reqs_manage_user/
    defaults: { _controller: jeb.snahp.acp_reqs:handle_manage_user}
jeb_snahp_acp_reqs_get_banned_dibbers:
    path: /snahp/acp_reqs_get_banned_dibbers/
    defaults: { _controller: jeb.snahp.acp_reqs:get_banned_dibbers}
jeb_snahp_acp_reqs_reset_user:
    path: /snahp/acp_reqs_reset_user/{username}/
    defaults: { _controller: jeb.snahp.acp_reqs:handle_reset_user}
    requirements:
        username: \S+
jeb_snahp_acp_reqs_userinfo:
    path: /snahp/acp_reqs_get_userinfo/{username}/
    defaults: { _controller: jeb.snahp.acp_reqs:get_userinfo}
    requirements:
        username: \S+
jeb_snahp_graveyard_request:
    path: /snahp/graveyard_request/
    defaults: { _controller: jeb.snahp.graveyard_request:handle}
# This is used for completely custom request form. Not implemented.
jeb_snahp_reqs_post:
    path: /snahp/reqs_post/{mode}/{fid}/
    defaults: { _controller: jeb.snahp.reqs_post:handle}
    requirements:
        mode: \S+
        fid: \d+
jeb_snahp_simulation:
    path: /snahp/simulation/{mode}/
    defaults: { _controller: jeb.snahp.simulation:handle}
    requirements:
        mode: \S+
jeb_snahp_mcp:
    path: /snahp/mcp/{mode}/
    defaults: { _controller: jeb.snahp.mcp:handle}
    requirements:
        mode: \S+
