jeb_snahp_admin:
    path: /snahp/admin/
    defaults: { _controller: jeb.snahp.admin:handle}
jeb_snahp_reqs:
    path: /snahp/reqs/{fid}/{tid}/{pid}/{mode}/
    defaults: { _controller: jeb.snahp.reqs:handle}
    requirements:
        fid: \d+
        tid: \d+
        pid: \d+
        mode: \d+
