imports:
    - { resource: parameters.yml }
    - { resource: cron.yml }
services:
    jeb.snahp.core:
        class: jeb\snahp\core\core
        abstract: true
        calls:
            - [set_user, ['@user']]
            - [set_template_context, ['@template_context']]
    jeb.snahp.base:
        class: jeb\snahp\core\base
        abstract: true
        arguments:
            - '%core.table_prefix%'
        calls:
            - [set_template_context, ['@template_context']]
            - [set_container,        ['@service_container']]
            - [set_user,             ['@user']]
            - [set_auth,             ['@auth']]
            - [set_request,          ['@request']]
            - [set_db,               ['@dbal.conn']]
            - [set_config,           ['@config']]
            - [set_helper,           ['@controller.helper']]
            - [set_language,         ['@language']]
            - [set_template,         ['@template']]
            - [set_notification,     ['@notification_manager']]
    jeb.snahp.service:
        class: jeb\snahp\service
        arguments:
            - '@user'
            - '%jeb.snahp.tables.snp_table%'
    jeb.snahp.request_listener:
        class: jeb\snahp\event\request_listener
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }
    jeb.snahp.listener:
        class: jeb\snahp\event\main_listener
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }
    jeb.snahp.registration_listener:
        class: jeb\snahp\event\registration_listener
        parent: jeb.snahp.base
        tags:
            - { name: event.listener }
    jeb.snahp.mod_listener:
        class: jeb\snahp\event\mod_listener
        parent: jeb.snahp.base
        tags:
            - { name: event.listener }
    jeb.snahp.acp_thanks:
        class: jeb\snahp\controller\acp_thanks
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.analytics:
        class: jeb\snahp\controller\analytics
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.thanks:
        class: jeb\snahp\controller\thanks
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.userscript:
        class: jeb\snahp\controller\userscript
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.template:
        class: jeb\snahp\controller\template
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.invite:
        class: jeb\snahp\controller\invite
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.acp_prune_users:
        class: jeb\snahp\controller\acp_prune_users
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.mdl:
        class: jeb\snahp\controller\mdl
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.reputation:
        class: jeb\snahp\controller\reputation
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.achievements:
        class: jeb\snahp\controller\achievements
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.digg:
        class: jeb\snahp\controller\digg
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.favorite:
        class: jeb\snahp\controller\favorite
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.search_util:
        class: jeb\snahp\controller\search_util
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.mcp:
        class: jeb\snahp\controller\mcp
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.simulation:
        class: jeb\snahp\controller\simulation
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
# Unimplemented
    jeb.snahp.reqs_post:
        class: jeb\snahp\controller\reqs_post
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.acp_fiximdb:
        class: jeb\snahp\controller\acp_fiximdb
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.acp_invite:
        class: jeb\snahp\controller\acp_invite
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.acp_reqs:
        class: jeb\snahp\controller\acp_reqs
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.reqs:
        class: jeb\snahp\controller\reqs
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.admin:
        class: jeb\snahp\controller\admin
        parent: jeb.snahp.base
        arguments:
            - '@jeb.snahp.topic_mover'
    jeb.snahp.notification.type.reputation:
        class: jeb\snahp\notification\reputation
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.user_notifications%'
            - '%tables.notifications%'
            - '@user_loader'
            - '@service_container'
        tags:
            - { name: notification.type }
    jeb.snahp.notification.type.digg:
        class: jeb\snahp\notification\digg
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.user_notifications%'
            - '%tables.notifications%'
            - '@user_loader'
            - '@service_container'
        tags:
            - { name: notification.type }
    jeb.snahp.notification.type.basic:
        class: jeb\snahp\notification\basic
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.user_notifications%'
            - '%tables.notifications%'
            - '@user_loader'
        tags:
            - { name: notification.type }
    jeb.snahp.topic_mover:
        class: jeb\snahp\core\topic_mover
        arguments:
            - '@user'
            - '@dbal.conn'
            - '@log'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'
    jeb.snahp.graveyard_request:
        class: jeb\snahp\controller\graveyard_request
        parent: jeb.snahp.base
        arguments:
            - '@jeb.snahp.topic_mover'
