imports:
    - { resource: parameters.yml }

services:
    jeb.snahp.core:
        class: jeb\snahp\core\core
        abstract: true
        calls:
            - [set_user, ['@user']]
            - [set_template_context, ['@template_context']]
    jeb.snahp.service:
        class: jeb\snahp\service
        arguments:
            - '@user'
            - '%jeb.snahp.tables.snp_table%'
    jeb.snahp.request_listener:
        class: jeb\snahp\event\request_listener
        parent: jeb.snahp.core
        arguments:
            - '@auth'
            - '@request'
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '%core.table_prefix%'
            - '@notification_manager'
        tags:
            - { name: event.listener }
    jeb.snahp.listener:
        class: jeb\snahp\event\main_listener
        parent: jeb.snahp.core
        arguments:
            - '@auth'
            - '@request'
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '%core.table_prefix%'
            - '@notification_manager'
        tags:
            - { name: event.listener }
    jeb.snahp.reqs:
        class: jeb\snahp\controller\reqs
        arguments:
            - '@user'
            - '@auth'
            - '@request'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@template'
            - '%core.table_prefix%'
            - '@notification_manager'
    jeb.snahp.admin:
        class: jeb\snahp\controller\admin
        arguments:
            - '@user'
            - '@auth'
            - '@request'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@template'
    jeb.snahp.notification.type.basic:
        class: jeb\snahp\notification\basic
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.user_notifications%'
            - '%tables.notifications%'
            - '@user_loader'
        tags:
            - { name: notification.type }
