imports:
    - { resource: logger.yml }
    - { resource: parameters.yml }
    - { resource: cron.yml }
    - { resource: economy/economy.yml }
    - { resource: wiki.yml }
    - { resource: parsers.yml }
    - { resource: notifications.yml }
    - { resource: database_manager.yml }
    - { resource: switchboard.yml }
    - { resource: form.yml }
    - { resource: foe_blocker/service.yml }
    - { resource: api_proxy/service.yml }
    - { resource: avatar/service.yml }
    - { resource: rh_tags/service.yml }
    - { resource: giftbox/service.yml }
    - { resource: invite/service.yml }
    - { resource: styles/service.yml }
    - { resource: handlebar/service.yml }
    - { resource: spotlight/service.yml }
    - { resource: cron/service.yml }
    - { resource: reputation/service.yml }
    - { resource: poi/service.yml }
services:
    jeb.snahp.core:
        class: jeb\snahp\core\core
        abstract: true
        calls:
            - [set_user, ['@user']]
            - [set_template_context, ['@template_context']]
    jeb.snahp.base:
        class: jeb\snahp\core\base
        abstract: true
        arguments:
            - '%core.table_prefix%'
        calls:
            - [set_template_context, ['@template_context']]
            - [set_container,        ['@service_container']]
            - [set_user,             ['@user']]
            - [set_auth,             ['@auth']]
            - [set_request,          ['@request']]
            - [set_db,               ['@dbal.conn']]
            - [set_config,           ['@config']]
            - [set_helper,           ['@controller.helper']]
            - [set_language,         ['@language']]
            - [set_template,         ['@template']]
            - [set_notification,     ['@notification_manager']]
            - [set_phpbb_root_path,  ['%core.root_path%']]
    jeb.snahp.service:
        class: jeb\snahp\service
        arguments:
            - '@user'
            - '%jeb.snahp.tables.snp_table%'
    jeb.snahp.request_listener:
        class: jeb\snahp\event\request_listener
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }
    jeb.snahp.listener:
        class: jeb\snahp\event\main_listener
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
            - '@jeb.snahp.user.user_inventory'
            - '@jeb.snahp.market.product_class'
        tags:
            - { name: event.listener }
    jeb.snahp.registration_listener:
        class: jeb\snahp\event\registration_listener
        parent: jeb.snahp.base
        tags:
            - { name: event.listener }
    jeb.snahp.thanks_listener:
        class: jeb\snahp\event\thanks_listener
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@config'
            - '@service_container'
            - '%jeb.snahp.tables%'
            - '@jeb.snahp.auth.user_auth'
        tags:
            - { name: event.listener }
    jeb.snahp.mod_listener:
        class: jeb\snahp\event\mod_listener
        parent: jeb.snahp.base
        tags:
            - { name: event.listener }
    jeb.snahp.acp_thanks:
        class: jeb\snahp\controller\acp_thanks
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.analytics:
        class: jeb\snahp\controller\analytics
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.thanks:
        class: jeb\snahp\controller\thanks
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.userscript:
        class: jeb\snahp\controller\userscript
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.template:
        class: jeb\snahp\controller\template
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.invite:
        class: jeb\snahp\controller\invite
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.acp_prune_users:
        class: jeb\snahp\controller\acp_prune_users
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.emotes:
        class: jeb\snahp\controller\emotes
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.help:
        class: jeb\snahp\controller\help
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.mdl:
        class: jeb\snahp\controller\mdl
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.achievements:
        class: jeb\snahp\controller\achievements
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.custom_rank:
        class: jeb\snahp\controller\custom_rank
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.digg:
        class: jeb\snahp\controller\digg
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.favorite:
        class: jeb\snahp\controller\favorite
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.search_util:
        class: jeb\snahp\controller\search_util
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.mcp:
        class: jeb\snahp\controller\mcp
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.simulation:
        class: jeb\snahp\controller\simulation
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
# Unimplemented
    jeb.snahp.reqs_post:
        class: jeb\snahp\controller\reqs_post
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.acp_fixmediainfo:
        class: jeb\snahp\controller\acp_fixmediainfo
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.acp_fiximdb:
        class: jeb\snahp\controller\acp_fiximdb
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.acp_invite:
        class: jeb\snahp\controller\acp_invite
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.acp_reqs:
        class: jeb\snahp\controller\acp_reqs
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.reqs:
        class: jeb\snahp\controller\reqs
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.admin:
        class: jeb\snahp\controller\admin
        parent: jeb.snahp.base
        arguments:
            - '@jeb.snahp.topic_mover'
    jeb.snahp.topic_mover:
        class: jeb\snahp\core\topic_mover
        arguments:
            - '@user'
            - '@dbal.conn'
            - '@log'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'
    jeb.snahp.graveyard_request:
        class: jeb\snahp\controller\graveyard_request
        parent: jeb.snahp.base
        arguments:
            - '@jeb.snahp.topic_mover'
    # BANK TRANSACTIONS
    jeb.snahp.bank:
        class: jeb\snahp\controller\bank
        parent: jeb.snahp.base
        arguments:
            - '@jeb.snahp.bank_helper'
    jeb.snahp.market_helper:
        class: jeb\snahp\core\market\market_helper
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@auth'
            - '@template'
            - '@user'
            - '@cache.driver'
            - '@service_container'
            - '%jeb.snahp.tables%'
    jeb.snahp.user_inventory_helper:
        class: jeb\snahp\core\user_inventory\user_inventory_helper
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@auth'
            - '@template'
            - '@user'
            - '@cache.driver'
            - '@service_container'
            - '%jeb.snahp.tables%'
    jeb.snahp.bank_helper:
        class: jeb\snahp\core\bank\bank_helper
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@auth'
            - '@template'
            - '@user'
            - '@cache.driver'
            - '@service_container'
            - '%jeb.snahp.tables%'
# AUTH
    jeb.snahp.auth.user_auth:
        class: jeb\snahp\core\auth\user_auth
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '@service_container'
# TEST
    jeb.snahp.test:
        class: jeb\snahp\controller\test
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '@config'
            - '@request'
            - '@template'
            - '@service_container'
            - '@controller.helper'
            - '@cache'
            - '%jeb.snahp.tables%'
            - '@jeb.snahp.auth.user_auth'
