imports:
    - { resource: parameters.yml }
    - { resource: cron.yml }
services:
    jeb.snahp.core:
        class: jeb\snahp\core\core
        abstract: true
        calls:
            - [set_user, ['@user']]
            - [set_template_context, ['@template_context']]
    jeb.snahp.base:
        class: jeb\snahp\core\base
        abstract: true
        arguments:
            - '%core.table_prefix%'
        calls:
            - [set_template_context, ['@template_context']]
            - [set_container,        ['@service_container']]
            - [set_user,             ['@user']]
            - [set_auth,             ['@auth']]
            - [set_request,          ['@request']]
            - [set_db,               ['@dbal.conn']]
            - [set_config,           ['@config']]
            - [set_helper,           ['@controller.helper']]
            - [set_language,         ['@language']]
            - [set_template,         ['@template']]
            - [set_notification,     ['@notification_manager']]
    jeb.snahp.service:
        class: jeb\snahp\service
        arguments:
            - '@user'
            - '%jeb.snahp.tables.snp_table%'
    jeb.snahp.request_listener:
        class: jeb\snahp\event\request_listener
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }
    jeb.snahp.listener:
        class: jeb\snahp\event\main_listener
        parent: jeb.snahp.core
        arguments:
            - '@auth'
            - '@request'
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '%core.table_prefix%'
            - '@notification_manager'
        tags:
            - { name: event.listener }
    jeb.snahp.mod_listener:
        class: jeb\snahp\event\mod_listener
        parent: jeb.snahp.core
        arguments:
            - '@auth'
            - '@request'
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '%core.table_prefix%'
            - '@notification_manager'
        tags:
            - { name: event.listener }
# Unimplemented
    jeb.snahp.reqs_post:
        class: jeb\snahp\controller\reqs_post
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.acp_reqs:
        class: jeb\snahp\controller\acp_reqs
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.reqs:
        class: jeb\snahp\controller\reqs
        parent: jeb.snahp.base
        arguments:
            - '%core.table_prefix%'
    jeb.snahp.admin:
        class: jeb\snahp\controller\admin
        parent: jeb.snahp.base
        arguments:
            - '@jeb.snahp.topic_mover'
    jeb.snahp.notification.type.basic:
        class: jeb\snahp\notification\basic
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.user_notifications%'
            - '%tables.notifications%'
            - '@user_loader'
        tags:
            - { name: notification.type }
    jeb.snahp.topic_mover:
        class: jeb\snahp\core\topic_mover
        arguments:
            - '@user'
            - '@dbal.conn'
            - '@log'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'
    jeb.snahp.graveyard_request:
        class: jeb\snahp\controller\graveyard_request
        parent: jeb.snahp.base
        arguments:
            - '@jeb.snahp.topic_mover'
