parameters:
    jeb.snahp.tables.snp_table: '%core.table_prefix%snp_table'
    jeb.snahp.tables: 
        req:    '%core.table_prefix%snahp_request'
        requsr: '%core.table_prefix%snahp_request_users'
        dibs:   '%core.table_prefix%snahp_dibs'
        bump_topic: '%core.table_prefix%snahp_bump_topic'
        invite: '%core.table_prefix%snahp_invite'
        invite_users: '%core.table_prefix%snahp_invite_users'
        thanks: '%core.table_prefix%thanks'
        thanks_users: '%core.table_prefix%thanks_users'
        tpl: '%core.table_prefix%snahp_tpl'
        manual_search_posts: '%core.table_prefix%snahp_manual_search_posts'
        digg_slave: '%core.table_prefix%snahp_digg_slave'
        digg_master: '%core.table_prefix%snahp_digg_master'
        achievements: '%core.table_prefix%snahp_achievements'
        reputation: '%core.table_prefix%snahp_reputation'
        styles: '%core.table_prefix%styles'
        notifications: '%core.table_prefix%notifications'
        notification_types: '%core.table_prefix%notification_types'
        user_notifications: '%core.table_prefix%user_notifications'
        bank_transactions: '%core.table_prefix%snahp_bank_transactions'
        bank_transaction_items: '%core.table_prefix%snahp_bank_transaction_items'
        bank_exchange_rates: '%core.table_prefix%snahp_bank_exchange_rates'
        mrkt_invoice_items: '%core.table_prefix%snahp_mrkt_invoice_items'
        mrkt_invoices: '%core.table_prefix%snahp_mrkt_invoices'
        mrkt_product_classes: '%core.table_prefix%snahp_mrkt_product_classes'
        user_inventory: '%core.table_prefix%snahp_user_inventory'
        custom_ranks: '%core.table_prefix%snahp_custom_ranks'
        log: '%core.table_prefix%snahp_log'
        wiki: '%core.table_prefix%snahp_wiki'
        foe: '%core.table_prefix%snahp_foe'
        tags_group_map: '%core.table_prefix%rh_topictags_group_map'
        tags_forum_map: '%core.table_prefix%rh_topictags_forum_map'
        giveaways: '%core.table_prefix%snahp_giveaways'
        cron_log: '%core.table_prefix%snahp_cron_log'

