imports:
  # - { resource: 'spotlight/parameters.yml' }
services:
  jeb.snahp.spotlight: # CONTROLLER
    class: jeb\snahp\controller\spotlight\spotlight
    arguments:
      - '@dbal.conn'
      - '@user'
      - '@config'
      - '@request'
      - '@template'
      - '@service_container'
      - '@controller.helper'
      - '%jeb.snahp.tables%'
      - '@jeb.snahp.auth.user_auth'
      - '@jeb.snahp.spotlight_helper'

  jeb.snahp.spotlight_helper: # HELPER
    class: jeb\snahp\core\spotlight\helper
    arguments:
      - '@dbal.conn'
      - '@user'
      - '@auth'
      - '@config'
      - '@config_text'
      - '@service_container'
      - '%jeb.snahp.tables%'
      - '@jeb.snahp.auth.user_auth'

  jeb.snahp.spotlight_listener: # EVENT LISTENER
    class: jeb\snahp\event\spotlight_listener
    arguments:
      - '@dbal.conn'
      - '@config'
      - '@user'
      - '@template'
      - '@service_container'
      - '%jeb.snahp.tables%'
      - '@jeb.snahp.auth.user_auth'
      - '@jeb.snahp.spotlight_helper'
    tags:
      - { name: event.listener }
