parameters:
    jeb.snahp.styles.banners:
        light: &light
            default: &default
                - https://i.imgur.com/Sg9lMpz.jpg
                - https://i.imgur.com/suBiXhh.jpg
                - https://i.imgur.com/AP2HCuV.jpg
                - https://i.imgur.com/fhIfMiB.jpg
            afternoon: *default
            evening:
                - https://i.imgur.com/8zrbBlY.jpg
                - https://i.imgur.com/LtW26ML.jpg
                - https://i.imgur.com/0qnRYwd.jpg
                - https://i.imgur.com/ImDrHDT.jpg
            latenight:
                - https://i.imgur.com/8guFD6o.jpg
                - https://i.imgur.com/lO859Bz.jpg
                - https://i.imgur.com/hq9VB9J.jpg
                - https://i.imgur.com/NkUPBcx.jpg
            twilight:
                - https://i.imgur.com/clN8dbq.jpg
                - https://i.imgur.com/OezJUxT.jpg
                - https://i.imgur.com/O2Ueo6L.jpg
                - https://i.imgur.com/MNzGLNi.jpg
            morning:
                - https://i.imgur.com/IeCiqNt.jpg
                - https://i.imgur.com/V3AKglj.jpg
                - https://i.imgur.com/dVne4LQ.jpg
                - https://i.imgur.com/MtzvvnJ.jpg
        dark: *light
        time_of_day:
            0: &zero 'latenight'
            1: 'twilight'
            2: 'twilight'
            3: 'twilight'
            4: 'twilight'
            5: 'twilight'
            6: 'morning'
            7: 'morning'
            8: 'morning'
            9: 'morning'
            10: 'morning'
            11: 'morning'
            12: 'afternoon'
            13: 'afternoon'
            14: 'afternoon'
            15: 'afternoon'
            16: 'afternoon'
            17: 'evening'
            18: 'evening'
            19: 'evening'
            20: 'evening'
            21: 'latenight'
            22: 'latenight'
            23: 'latenight'
            24: *zero
