parameters:
    jeb.snahp.styles.banners:
        light: &light
            default: &default
                - https://i.imgur.com/sqWHc2h.png
                # - https://i.imgur.com/FIcm4d7.png
            afternoon: *default
            evening:
                - https://i.imgur.com/SxCc3z9.jpg
                # - https://i.imgur.com/Fuum0fj.png
                # - https://i.imgur.com/ybtvdxb.png
            latenight:
                - https://i.imgur.com/aw2s9vT.jpg
                # - https://i.imgur.com/47konmN.jpg
                # - https://i.imgur.com/6Pk55So.jpg
            twilight:
                - https://i.imgur.com/35Jo4B4.png
                # - https://i.imgur.com/4gJp2uo.png
                # - https://i.imgur.com/hOGLP3F.jpg
            morning:
                - https://i.imgur.com/rzWMxJ6.jpg
                # - https://i.imgur.com/59rc8Ah.jpg
        dark: *light
        time_of_day:
            0: &zero 'latenight'
            1: 'twilight'
            2: 'twilight'
            3: 'twilight'
            4: 'twilight'
            5: 'twilight'
            6: 'morning'
            7: 'morning'
            8: 'morning'
            9: 'morning'
            10: 'morning'
            11: 'morning'
            12: 'afternoon'
            13: 'afternoon'
            14: 'afternoon'
            15: 'afternoon'
            16: 'afternoon'
            17: 'evening'
            18: 'evening'
            19: 'evening'
            20: 'evening'
            21: 'latenight'
            22: 'latenight'
            23: 'latenight'
            24: *zero
