parameters:
    jeb.snahp.styles.banners:
        light: &light
            default: &default
                - https://i.imgur.com/YJYPp1Y.jpg
            afternoon: *default
            evening:
                - https://i.imgur.com/IckC5Cz.png
                - https://i.imgur.com/BFSPBWk.jpg
            latenight:
                - https://i.imgur.com/Kp5Bz34.png
                - https://i.imgur.com/oGB7dlG.png
            twilight:
                - https://i.imgur.com/vNH2eQC.png
                - https://i.imgur.com/sJTxMiQ.png
            morning:
                - https://i.imgur.com/7szjSt7.jpg
        dark: *light
