parameters:
    jeb.snahp.styles.banners:
        - https://i.imgur.com/T3N1W2E.jpg
        # - https://i.imgur.com/fyuXOfH.jpg
        - https://i.imgur.com/9PPMTqy.jpg
        - https://i.imgur.com/wRcfdiI.jpg
        - https://i.imgur.com/9vg3rLF.jpg
        - https://i.imgur.com/CD5xjqP.jpg
        - https://i.imgur.com/sme3T8e.jpg
        # - https://i.imgur.com/8uLgcue.jpg
        # - https://i.imgur.com/yFIBf8i.jpg
        - https://i.imgur.com/SQXr82S.jpg
        - https://i.imgur.com/2yicRlO.jpg
        - https://i.imgur.com/rQSvvDL.jpg
        - https://i.imgur.com/ZIicrw9.jpg
        # - https://i.imgur.com/Y0wSZgV.jpg
        - https://i.imgur.com/uP42Ry7.jpg
        # - https://i.imgur.com/Wsz1JVw.jpg
        # - https://i.imgur.com/I9Z7LQh.jpg
        - https://i.imgur.com/R3tAIks.jpg
        - https://i.imgur.com/z1sguFK.jpg
        - https://i.imgur.com/rQPGkh8.jpg
        - https://i.imgur.com/CbDdxcd.jpg
        - https://i.imgur.com/5kzpWh2.jpg
        # - https://i.imgur.com/DWhM0wF.jpg
        # - https://i.imgur.com/tSePvjd.jpg
        # - https://i.imgur.com/RjNxada.jpg
        # - https://i.imgur.com/PHhDyIz.jpg
        # - https://i.imgur.com/2YRzfUW.jpg
        # - https://i.imgur.com/4YQNhLg.jpg
        # - https://i.imgur.com/H6aC09e.jpg
        # - https://i.imgur.com/RvCZLMu.jpg
        # - https://i.imgur.com/b0TtOlw.jpg
        # - https://i.imgur.com/3D6dAyG.jpg
        # - https://i.imgur.com/62bPvTE.jpg
        # - https://i.imgur.com/5DABDS3.jpg
        # - https://i.imgur.com/Z5xZCb4.jpg
        # - https://i.imgur.com/Kq8ZdmY.jpg
        # - https://i.imgur.com/w9INzxl.jpg
        # - https://i.imgur.com/8Ff2KVR.jpg
        # - https://i.imgur.com/2gNuCQ4.jpg
        # - https://i.imgur.com/gv49ALo.jpg

