services:
  jeb.snahp.poi: # CONTROLLER
    class: jeb\snahp\controller\poi\poi
    arguments:
      - '@dbal.conn'
      - '@user'
      - '@config'
      - '@request'
      - '@template'
      - '@service_container'
      - '@controller.helper'
      - '%jeb.snahp.tables%'
      - '@jeb.snahp.auth.user_auth'
