imports:
    - { resource: 'foe_blocker/parameters.yml' }
services:
    jeb.snahp.foe_blocker:
        class: jeb\snahp\controller\foe_blocker\foe_blocker
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@config'
            - '@request'
            - '@template'
            - '@service_container'
            - '@controller.helper'
            - '%jeb.snahp.tables%'
            - '@jeb.snahp.auth.user_auth'
            - '@jeb.snahp.foe_blocker_helper'
    jeb.snahp.foe_blocker_helper:
        class: jeb\snahp\core\foe_blocker\helper
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '@service_container'
            - '%jeb.snahp.tables%'
            - '@jeb.snahp.auth.user_auth'
    jeb.snahp.foe_listener:
        class: jeb\snahp\event\foe_listener
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@user'
            - '@template'
            - '@service_container'
            - '%jeb.snahp.tables%'
            - '@jeb.snahp.auth.user_auth'
            - '@jeb.snahp.foe_blocker_helper'
        tags:
            - { name: event.listener }
