# imports:
#     - { resource: 'dir/parameters.yml' }
services:

##########
#  View  #
##########


##############
#  API VIEW  #
##############

    jeb.snahp.Apps.TopicUpdateTicker.EntryListCreateAPIView:
        class: jeb\snahp\Apps\TopicUpdateTicker\EntryListCreateAPIView
        arguments:
            - @request
            - @jeb.snahp.auth.user_auth
            - @jeb.snahp.Apps.TopicUpdateTicker.Models.Entry
            - @jeb.snahp.Apps.TopicUpdateTicker.EntryPermission
    jeb.snahp.Apps.TopicUpdateTicker.EntryRetrieveUpdateDestroyAPIView:
        class: jeb\snahp\Apps\TopicUpdateTicker\EntryRetrieveUpdateDestroyAPIView
        arguments:
            - @request
            - @jeb.snahp.auth.user_auth
            - @jeb.snahp.Apps.TopicUpdateTicker.Models.Entry
            - @jeb.snahp.Apps.TopicUpdateTicker.EntryPermission


############
#  HELPER  #
############


###########
#  MODEL  #
###########


    jeb.snahp.Apps.TopicUpdateTicker.Models.Entry:
        class: jeb\snahp\Apps\TopicUpdateTicker\Models\Entry


################
#  PERMISSION  #
################


    jeb.snahp.Apps.TopicUpdateTicker.EntryPermission:
        class: jeb\snahp\Apps\TopicUpdateTicker\EntryPermission
        arguments:
            - @dbal.conn
            - @jeb.snahp.auth.user_auth


####################
#  EVENT LISTENER  #
####################
