# imports:
#     - { resource: 'dir/parameters.yml' }
services:

##########
#  View  #
##########

    jeb.snahp.Apps.TopicUpdateTicker.TopicUpdateTickerController:
        class: jeb\snahp\Apps\TopicUpdateTicker\TopicUpdateTickerController
        arguments:
            - @dbal.conn
            - @user
            - @config
            - @request
            - @template
            - @service_container
            - @controller.helper
            - %jeb.snahp.tables%
            - @jeb.snahp.auth.user_auth
            - @jeb.snahp.Apps.TopicUpdateTicker.TopicUpdateTickerHelper

##############
#  API VIEW  #
##############

    jeb.snahp.Apps.TopicUpdateTicker.EntryListCreateAPIView:
        class: jeb\snahp\Apps\TopicUpdateTicker\EntryListCreateAPIView
        arguments:
            - @request
            - @jeb.snahp.auth.user_auth
            - @jeb.snahp.Apps.TopicUpdateTicker.Models.Entry
    jeb.snahp.Apps.TopicUpdateTicker.EntryRetrieveUpdateDestroyAPIView:
        class: jeb\snahp\Apps\TopicUpdateTicker\EntryRetrieveUpdateDestroyAPIView
        arguments:
            - @request
            - @jeb.snahp.auth.user_auth
            - @jeb.snahp.Apps.TopicUpdateTicker.Models.Entry


############
#  HELPER  #
############


    jeb.snahp.Apps.TopicUpdateTicker.TopicUpdateTickerHelper:
        class: jeb\snahp\Apps\TopicUpdateTicker\TopicUpdateTickerHelper
        arguments:
            - @dbal.conn
            - @user
            - @template
            - %jeb.snahp.tables%
            - @jeb.snahp.auth.user_auth


###########
#  MODEL  #
###########


    jeb.snahp.Apps.TopicUpdateTicker.Models.Entry:
        class: jeb\snahp\Apps\TopicUpdateTicker\Models\Entry


####################
#  EVENT LISTENER  #
####################


    jeb.snahp.Apps.TopicUpdateTicker.TopicUpdateTickerEventListener:
        class: jeb\snahp\Apps\TopicUpdateTicker\TopicUpdateTickerEventListener
        arguments:
            - @user
            - @config
            - @jeb.snahp.auth.user_auth
            - @jeb.snahp.Apps.TopicUpdateTicker.TopicUpdateTickerHelper
        tags:
            - { name: event.listener }
