imports:
    - { resource: ./query/service.yml }

services:
    jeb.snahp.Apps.Core.Db.QuerySetFactory:
        class: jeb\snahp\Apps\Core\Db\QuerySetFactory
        arguments:
            - "@dbal.conn"
