parameters:
  jeb.snahp.avatar.badge.users:


    22391: #SampaD22
      queue:
        - 'encoder'
      data:
        encoder:
          template_type: 'alias'
          alias: '.QxR. SAMPA'
          tagname: 'SAMPA'
    161958: #eserafinojr
      queue:
        - 'encoder'
        - 'audio_expert'
      data:
        encoder:
          tagname: 'EPS'
        audio_expert:
    150397: #3XO
      queue:
        - 'encoder'
      data:
        encoder:
          tagname: '3xO'
    156: #MKED
      queue:
        - 'encoder'
      data:
        encoder:
          tagname: 'MKED'
    162225: #magiin
      queue:
        - 'encoder'
      data:
        encoder:
          tagname: 'MaG'
    94091: #Bluespots
      queue:
        - 'encoder'
        - 'anime_pack'
      data:
        encoder:
          tagname: 'Bluespots'
        anime_pack:
          title: 'Regional Director of the International Bureau for Preservation and Dissemination of Animated Art'
          url: '/viewtopic.php?f=84&t=114147'
    111: #SkumDog
      queue:
        - 'encoder'
      data:
        encoder:
          template_type: 'alias'
          alias: '$ Millionaire $'
          tagname: 'SkumDog'
    8324: #Smurf
      queue:
        - 'encoder'
      data:
        encoder:
          tagname: 'Smurf'
    5495: #Fantompoke
      queue:
        - 'encoder'
      data:
        encoder:
          tagname: 'Poke'
    3068: #Koyumu
      queue:
        - 'encoder'
        - 'anime_pack'
      data:
        encoder:
          tagname: 'Koyumu'
        anime_pack:
          title: 'Regional Director of the International Bureau for Preservation and Dissemination of Animated Art'
          url: '/viewtopic.php?f=56&t=5174'
    133765: #qebehsenue
      queue:
        - 'encoder'
      data:
        encoder:
          tagname: 'qebe'
    126178: #PrivateCodex
      queue:
        - 'encoder'
      data:
        encoder:
          tagname: 'PvtCdx'
    113291: #ItchyFinger
      queue:
        - 'encoder'
      data:
        encoder:
          tagname: 'ItchyFinger'
    93017: #HandsMcgee
      queue:
        - 'encoder'
      data:
        encoder:
          tagname: 'HANDS'
    154540: #DASTEREOGURU
      queue:
        - 'encoder'
      data:
        encoder:
          tagname: 'DSG'

    12694: #pandacircus
      queue:
        - 'audio_expert'
      data:
        audio_expert:
    2585: #Oldvcrguy
      queue:
        - 'drunken_master'
      data:
        drunken_master:
          url: '/viewtopic.php?f=73&t=26470'
    49485: #bonesandbillyclubs
      queue:
        - 'anime_pack'
      data:
        anime_pack:
          title: 'President of the International Bureau for Preservation and Dissemination of Animated Art'
          url: '/viewtopic.php?f=13&t=34584'
          img_url: 'https://i.imgur.com/PwBDgBQ.png'
    58626: #slipstream
      queue:
        - 'anime_pack'
      data:
        anime_pack:
          title: 'Regional Director of the International Bureau for Preservation and Dissemination of Animated Art'
          url: '/viewtopic.php?f=13&t=112503'
    37031: #ski77
      queue:
        - 'anime_pack'
        - 'updater'
      data:
        anime_pack:
          title: 'Regional Director of the International Bureau for Preservation and Dissemination of Animated Art'
          url: '/viewtopic.php?f=84&t=30484'
        updater:
          title: 'Perpetual Energy Machine, Model 101'
          url: '/search.php?keywords=UPDATING&terms=all&author_id=37031&sc=1&sf=titleonly&sr=topics&sk=x&sd=d&st=0&ch=300&t=0&submit=Search'
          img_url: 'https://i.imgur.com/LBcQOv1.png'
    50759: #chamako
      queue:
        - 'updater'
      data:
        updater:
          url: '/search.php?keywords=update&terms=all&author_id=50759&sc=1&sf=titleonly&sr=topics&sk=x&sd=d&st=0&ch=300&t=0&submit=Search'
    608: #omega59
      queue:
        - 'game_machine'
      data:
        game_machine:
          url: '/search.php?keywords=&terms=any&author_id=608&fid[]=10&sc=1&sf=titleonly&sr=topics&sk=x&sd=d&st=0&ch=300&t=0&submit=Search'
    119546: #GP10Ellison
      queue:
        - 'the_oracle'
        - 'trekki'
      data:
        the_oracle:
          url: '/viewtopic.php?f=37&t=110567'
        trekki:
          url: '/viewtopic.php?f=33&t=127131'
    61485: #Existence
      queue:
        - 'adobe_infinity'
      data:
        adobe_infinity:
          url: '/search.php?keywords=adobe&terms=any&author_id=61485&fid[]=9&sc=1&sf=titleonly&sr=topics&sk=x&sd=d&st=0&ch=300&t=0&submit=Search'
    2573: #perpetualmotions
      queue:
        - 'trekki'
      data:
        trekki:
          url: '/viewtopic.php?f=74&t=173091'
          img_url: 'https://i.imgur.com/hJ6Vchq.png'
    25790: #tituspullo
      queue:
        - 'james_bond'
      data:
        james_bond:
          url: '/viewtopic.php?f=56&t=5648'
    51956: #Mimccann
      queue:
        - 'trekki'
      data:
        trekki:
          url: '/viewtopic.php?f=74&t=173967'
    83907: #koolkunz
      queue:
        - 'encoder'
      data:
        encoder:
          tagname: 'K1tKat'


  # PROCESSOR DEFINITIONS
  jeb.snahp.avatar.badge.items:
    trekki:
      data:
        title:
          - 'KHAAANNN!'
          - 'To boldly go where no man has gone before.'
          - 'You can use logic to justify almost anything. That''s its power. And its flaw.'
          - 'But we''re going to learn from these mistakes. That''s what being human is all about.'
          - 'Our species can only survive if we have obstacles to overcome.'
          - 'Sometimes a feeling is all we humans have to go on.'
          - 'Sometimes the universe allows for the making of unexpected memories.'
          - 'Live long, and prosper.'
          - 'Things are only impossible until they''re not.'
        img_url: 'https://i.imgur.com/JEbCl63.png'
        class: 'trekki'
      template:
        basic:
          fields:
            - 'title'
            - 'img_url'
            - 'url'
            - 'class'
          html: '<span title="{title}"><a href="{url}"><img src="{img_url}" class="avatar_badge {class}"></img></a></span>'
    james_bond:
      override:
        style_type:
          light:
            img_url: 'https://i.imgur.com/Gg4xPaI.png'
          dark:
            img_url: 'https://i.imgur.com/pMmcsTk.png'
      data:
        title: 'Shaken, Not Stirred.'
        img_url: 'https://i.imgur.com/Gg4xPaI.png'
      template:
        basic:
          fields:
            - 'title'
            - 'img_url'
            - 'url'
          html: '<span title="{title}"><a href="{url}"><img src="{img_url}" class="avatar_badge adobe_infinity"></img></a></span>'
    adobe_infinity:
      data:
        title: 'To Adobe and Beyond!'
        img_url: 'https://i.imgur.com/pIFLOKL.png'
      template:
        basic:
          fields:
            - 'title'
            - 'img_url'
            - 'url'
          html: '<span title="{title}"><a href="{url}"><img src="{img_url}" class="avatar_badge adobe_infinity"></img></a></span>'
    game_machine:
      data:
        img_url: 'https://i.imgur.com/Uo7648y.png'
        title:
          - 'The Game Theory'
          - 'No game, no life!'
      template:
        basic:
          fields:
            - 'title'
            - 'img_url'
            - 'url'
          html: '<span title="{title}"><a href="{url}"><img src="{img_url}" class="avatar_badge game_machine"></img></a></span>'
    the_oracle:
      data:
        title:
          - 'Those who do not read history are doomed to repeat it.'
          - 'γνῶθι σεαυτόν'
          - 'An unsophisticated forecaster uses statistics as a drunken man uses lamp-posts - for support rather than for illumination.'
          - 'Quoth the raven, &quot;Nevermore!&quot;'
          - 'To expect defeat is nine-tenths of defeat itself.'
          - 'Invention, it must be humbly admitted, does not consist in creating out of void, but out of chaos.'
          - 'To love another person is to see the face of God.'
          - 'Our words are giants when they do us an injury, and dwarfs when they do us a service.'
          - 'Only mothers can think of the future - because they give birth to it in their children.'
          - 'We must not allow the clock and the calendar to blind us to the fact that each moment of life is a miracle and mystery.'
          - 'Every branch of human knowledge, if traced up to its source and final principles, vanishes into mystery.'
          - 'Happiness is a butterfly, which when pursued, is always just beyond your grasp, but which, if you will sit down quietly, may alight upon you.'
          - 'No amount of evidence will ever persuade an idiot.'
          - 'It is better to have dreamed a thousand dreams that never were than never to have dreamed at all.'
          - 'When you look at me, when you think of me, I am in paradise.'
          - 'The task of leadership is not to put greatness into people, but to elicit it, for the greatness is there already.'
          - 'Three things in human life are important. The first is to be kind. The second is to be kind. And the third is to be kind.'
          - 'There is pleasure in the pathless woods, there is rapture in the lonely shore, there is society where none intrudes, by the deep sea, and music in its roar; I love not Man the less, but Nature more.'
          - 'The most important thing in life is to stop saying &quot;I wish&quot; and start saying &quot;I will.&quot; Consider nothing impossible, then treat possibilities as probabilities.'
          - 'Speak when you are angry and you will make the best speech you will ever regret.'
          - 'If you make it a habit not to blame others, you will feel the growth of the ability to love in your soul, and you will see the growth of goodness in your life.'
          - 'Choose love not in the shallows but in the deep.'
          - 'Three grand essentials to happiness in this life are something to do, something to love, and something to hope for.'
          - 'Those that go searching for love only make manifest their own lovelessness, and the loveless never find love, only the loving find love, and they never have to seek for it.'
          - 'There are two ways of spreading light: to be the candle or the mirror that reflects it.'
        img_url: 'https://i.imgur.com/qNw8qDZ.png'
      template:
        basic:
          fields:
            - 'title'
            - 'img_url'
            - 'url'
          html: '<span title="{title}"><a href="{url}"><img src="{img_url}" class="avatar_badge the_oracle"></img></a></span>'
    drunken_master:
      data:
        title: 'Drunken Master'
        img_url: 'https://i.imgur.com/FxX4vma.png'
      template:
        basic:
          fields:
            - 'title'
            - 'img_url'
            - 'url'
          html: '<span title="{title}"><a href="{url}"><img src="{img_url}" class="avatar_badge maxh_36"></img></a></span>'
    audio_expert:
      data:
        title: 'Audio Expert'
        img_url: 'https://i.imgur.com/N0fWbFu.png'
        img_css: 'avatar_badge maxh_24'
      template:
        basic:
          fields:
            - 'title'
            - 'img_url'
            - 'img_css'
          html: '<div title="{title}" class="audio_expert"></div>'
          html: '<span title="{title}"><img src="{img_url}" class="{img_css}"></img></span>'
    updater:
      data:
        title: 'Perpetual Energy Machine'
        img_url: 'https://i.imgur.com/rgplXx8.png'
      template:
        basic:
          fields:
            - 'title'
            - 'url'
            - 'img_url'
          html: '<span title="{title}"><a href="{url}" target="_blank"><img src="{img_url}" class="avatar_badge maxh_24"></img></a></span>'
    anime_pack:
      data:
        title: 'International Bureau for Preservation and Dissemination of Animated Art'
        img_url: 'https://i.imgur.com/gTTbWym.png'
      template:
        basic:
          fields:
            - 'title'
            - 'url'
            - 'img_url'
          html: '<span title="{title}"><a href="{url}" target="_blank"><img class="avatar_badge maxh_36" src="{img_url}"></img></a></span>'
    encoder_group:
      data:
      template:
        basic:
          fields:
            - 'groupname'
            - 'user_colour'
          html: '<span style="color:#{user_colour};">.{groupname}. </span>'
    encoder:
      data:
          title: 'Encoder'
      template:
        basic:
          fields: &fields
            - 'title'
            - 'user_id'
            - 'tagname'
            - 'username'
            - 'user_colour'
          html: '<div title="{title}" style="margin-top: 1px; margin-bottom: 1px;"><a href="/search.php?keywords={tagname}&terms=all&author_id={user_id}&sc=1&sf=titleonly&sr=topics&sk=x&sd=d&st=0&ch=300&t=0&submit=Search" target="_blank"><span style="color:#{user_colour} !important;">{tagname}</span></a></div>'
        alias:
          fields:
            - 'alias'
            - 'title'
            - 'user_id'
            - 'tagname'
            - 'username'
            - 'user_colour'
          html: '<div title="{title}" style="margin-top: 1px; margin-bottom: 1px;"><a href="/search.php?keywords={tagname}&terms=all&author_id={user_id}&sc=1&sf=titleonly&sr=topics&sk=x&sd=d&st=0&ch=300&t=0&submit=Search" target="_blank"><span style="color:#{user_colour} !important;">{alias}</span></a></div>'
